-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE*OS.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT P
INNER JOIN OFFLINE_SALE OS ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(P.PRICE*OS.SALES_AMOUNT) DESC, P.PRODUCT_CODE ASC;