-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH
    INNER JOIN ICECREAM_INFO I ON I.FLAVOR = FH.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;